######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "images/logo/horizontal.svg"
logo_on_black: "images/logo/horizontal.svg"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["images/social-preview.svg"]

crs:
  release_url_prefix: "https://github.com/coreruleset/coreruleset/releases/tag"
  latest_major_version: "4.29.0"
  prev_major_version: "3.3.10"
  lts_v4_version: "4.25.1"

github:
  repo_url: "https://github.com/coreruleset/website/blob/main"
  show_edit_link: true

social_links:
  bluesky: "https://bsky.app/profile/coreruleset.bsky.social"
  devstats: ""
  discord: ""
  facebook: ""
  flickr: ""
  github: "https://github.com/coreruleset"
  instagram: ""
  landscape: ""
  linkedin: "https://www.linkedin.com/company/owasp-crs"
  mastodon: "https://infosec.exchange/@coreruleset"
  pinterest: ""
  rss: ""
  slack: "https://owasp.slack.com/archives/CBKGH8A5P"
  stackoverflow: ""
  threads: ""
  twitter: "https://twitter.com/coreruleset"
  x: "https://x.com/coreruleset"
  youtube: "https://www.youtube.com/channel/UCIoIEzbm34kczIvVyPGYBfg"

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: true
